[package]
name = "min-subseq-transducer"
version = "0.1.0"
edition = "2021"

[profile.dev]
debug = true
overflow-checks = false

[dependencies]
csv = "1.2.2"
serde = { version = "1.0.164", features = ["serde_derive"] }
